### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by sternschnaube** [IzukiKa/RPG-Titles#5]
Hello, great mod!! 😊
I have three suggestions.
First: Could you add please a customizable timer, how long the biome name would appear?
Second: Custom color support / maybe biome type defined colors / remove the "Biome:" from it, since it's clear what it means.
Third: I'm not sure if the commands working server wide or just for the player who was triggering it. 
If they working server wide, it would be nicee to group it individual to every player.

Thanks already.

**Comment by IzukiKa** [comment]
Hi! Thanks for checking out my mod!
1) Its possible, but I would have to re-write a lot of the pack because currently it is just always on or off, so I'm probably not going to do that for now
2) The colours are currently used to signify what "biome source" the biome is from. Currently only vanilla and Terralith biomes are supported - where vanilla is light green and Terralith is light blue (other sources are planned soon). 
3) The commands are player-based, not server-based so every player can have their own config!

**Comment by sternschnaube** [comment]
Hello, thanks for the answer.

Good to know about point two and three 👍🏿
Would be great to have point one "optimazed", but I can understand the hard work behind it.

**Comment by IzukiKa** [comment]
Point 1 is definitely something I might look into when Minecraft 1.20 comes out as I was already planning to re-write it for that update. Thanks again for looking at my mod!
